# -*- coding: utf-8 -*-
"""Summarizer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12qFoNOOPF2q-jk4LTBU-nzBHl3Qn908W
"""

!pip install bert-extractive-summarizer

from summarizer import Summarizer

patient_data = {
    "patient": {
        "id": "98765",
        "history": [
            {
                "symptoms": ["fatigue", "headache"],
                "diagnosis": "Migraine",
                "medications": ["ibuprofen"],
                "notes": "Patient reports persistent headaches and fatigue. Prescribed ibuprofen for relief."
            },
            {
                "symptoms": ["nausea", "vomiting"],
                "diagnosis": "Gastroenteritis",
                "medications": ["antiemetics", "oral rehydration solution"],
                "notes": "Patient experienced nausea and vomiting. Diagnosed with gastroenteritis. Prescribed antiemetics and oral rehydration solution."
            },
            {
                "symptoms": ["joint pain", "rash"],
                "diagnosis": "Rheumatoid Arthritis",
                "medications": ["NSAIDs", "corticosteroids"],
                "notes": "Joint pain and rash reported. Diagnosed with rheumatoid arthritis. Prescribed NSAIDs and corticosteroids."
            },
            {
                "symptoms": ["shortness of breath", "chest pain"],
                "diagnosis": "Pneumonia",
                "medications": ["antibiotics", "bronchodilators"],
                "notes": "Severe respiratory symptoms observed. Diagnosed with pneumonia. Prescribed antibiotics and bronchodilators."
            },
            {
                "symptoms": ["fever", "cough"],
                "diagnosis": "Influenza",
                "medications": ["antivirals", "acetaminophen"],
                "notes": "Patient presents with fever and cough. Diagnosed with influenza. Prescribed antivirals and acetaminophen."
            },
            {
                "symptoms": ["abdominal pain", "diarrhea"],
                "diagnosis": "Gastrointestinal Infection",
                "medications": ["antibiotics", "antidiarrheals"],
                "notes": "Complaints of abdominal pain and diarrhea. Diagnosed with gastrointestinal infection. Prescribed antibiotics and antidiarrheals."
            },
            {
                "symptoms": ["confusion", "memory loss"],
                "diagnosis": "Alzheimer's Disease",
                "medications": ["cholinesterase inhibitors", "memantine"],
                "notes": "Patient and caregivers report confusion and memory loss. Diagnosed with Alzheimer's disease. Prescribed cholinesterase inhibitors and memantine."
            },
            {
                "symptoms": ["muscle weakness", "tingling sensations"],
                "diagnosis": "Multiple Sclerosis",
                "medications": ["disease-modifying therapies", "corticosteroids"],
                "notes": "New symptoms of muscle weakness and tingling sensations. Diagnosed with multiple sclerosis. Prescribed disease-modifying therapies and corticosteroids."
            },
            {
                "symptoms": ["insomnia"],
                "diagnosis": "Bipolar Disorder",
                "medications": ["mood stabilizers", "antipsychotics"],
                "notes": "Patient reports mood swings and insomnia. Diagnosed with bipolar disorder. Prescribed mood stabilizers and antipsychotics."
            },
            {
                "symptoms": ["difficulty breathing", "wheezing"],
                "diagnosis": "Asthma",
                "medications": ["inhaled corticosteroids", "bronchodilators"],
                "notes": "Experiencing difficulty breathing and wheezing. Diagnosed with asthma. Prescribed inhaled corticosteroids and bronchodilators."
            },
            {
                "symptoms": ["abnormal bleeding", "fatigue"],
                "diagnosis": "Hemophilia",
                "medications": ["clotting factor replacement"],
                "notes": "Reports abnormal bleeding episodes and fatigue. Diagnosed with hemophilia. Prescribed clotting factor replacement therapy."
            },
            {
                "symptoms": ["joint stiffness", "fatigue"],
                "diagnosis": "Fibromyalgia",
                "medications": ["analgesics", "muscle relaxants"],
                "notes": "Complaints of joint stiffness and persistent fatigue. Diagnosed with fibromyalgia. Prescribed analgesics and muscle relaxants."
            },
            {
                "symptoms": ["skin rash", "itching"],
                "diagnosis": "Allergic Dermatitis",
                "medications": ["antihistamines", "topical steroids"],
                "notes": "Developed skin rash and itching. Diagnosed with allergic dermatitis. Prescribed antihistamines and topical steroids."
            },
            {
                "symptoms": ["digestive issues", "heartburn"],
                "diagnosis": "Gastroesophageal Reflux Disease (GERD)",
                "medications": ["proton pump inhibitors", "antacids"],
                "notes": "Experiencing digestive issues and heartburn. Diagnosed with GERD. Prescribed proton pump inhibitors and antacids."
            },
            {
                "symptoms": ["numbness", "tingling"],
                "diagnosis": "Peripheral Neuropathy",
                "medications": ["nerve pain medications", "physical therapy"],
                "notes": "Reports numbness and tingling sensations. Diagnosed with peripheral neuropathy. Prescribed nerve pain medications and recommended physical therapy."
            },
            {
                "symptoms": ["migratory joint pain", "fever"],
                "diagnosis": "Lupus",
                "medications": ["immunosuppressants", "nonsteroidal anti-inflammatory drugs (NSAIDs)"],
                "notes": "Experiencing migratory joint pain and fever. Diagnosed with lupus. Prescribed immunosuppressants and NSAIDs."
            },
            {
                "symptoms": ["vision changes", "eye pain"],
                "diagnosis": "Glaucoma",
                "medications": ["eye drops", "beta blockers"],
                "notes": "Notices vision changes and experiences eye pain. Diagnosed with glaucoma. Prescribed eye drops and beta blockers."
            },
            {
                "symptoms": ["muscle cramps", "fatigue"],
                "diagnosis": "Chronic Fatigue Syndrome",
                "medications": ["symptomatic treatment", "cognitive-behavioral therapy (CBT)"],
                "notes": "Frequent muscle cramps and persistent fatigue reported. Diagnosed with chronic fatigue syndrome. Prescribed symptomatic treatment and recommended cognitive-behavioral therapy (CBT)."
            },
            {
                "symptoms": ["difficulty swallowing", "weight loss"],
                "diagnosis": "Esophageal Cancer",
                "medications": ["chemotherapy", "radiation therapy"],
                "notes": "Experiencing difficulty swallowing and significant weight loss. Diagnosed with esophageal cancer. Recommended chemotherapy and radiation therapy."
            },
            {
                "symptoms": ["dizziness", "nausea"],
                "diagnosis": "Vertigo",
                "medications": ["vestibular suppressants", "antiemetics"],
                "notes": "Patient complains of persistent dizziness and nausea. Diagnosed with vertigo. Prescribed vestibular suppressants and antiemetics."
            },
            {
                "symptoms": ["chest tightness", "shortness of breath"],
                "diagnosis": "Chronic Obstructive Pulmonary Disease (COPD)",
                "medications": ["bronchodilators", "inhaled corticosteroids"],
                "notes": "Experiencing chest tightness and difficulty breathing. Diagnosed with COPD. Prescribed bronchodilators and inhaled corticosteroids."
            },
            {
                "symptoms": ["abdominal swelling", "fatigue"],
                "diagnosis": "Liver Cirrhosis",
                "medications": ["diuretics", "liver support medications"],
                "notes": "Reports abdominal swelling and persistent fatigue. Diagnosed with liver cirrhosis. Prescribed diuretics and liver support medications."
            },
            {
                "symptoms": ["mood swings", "loss of interest"],
                "diagnosis": "Major Depressive Disorder",
                "medications": ["antidepressants", "psychotherapy"],
                "notes": "Patient exhibits mood swings and loss of interest. Diagnosed with major depressive disorder. Prescribed antidepressants and recommended psychotherapy."
            },
            {
                "symptoms": ["seizures", "confusion"],
                "diagnosis": "Epilepsy",
                "medications": ["antiepileptic drugs", "neurologist referral"],
                "notes": "Suffered from seizures and confusion. Diagnosed with epilepsy. Prescribed antiepileptic drugs and referred to a neurologist for further evaluation."
            },
            {
                "symptoms": ["abnormal heartbeat", "dizziness"],
                "diagnosis": "Atrial Fibrillation",
                "medications": ["blood thinners", "heart rate control medications"],
                "notes": "Reports abnormal heartbeat and dizziness. Diagnosed with atrial fibrillation. Prescribed blood thinners and heart rate control medications."
            },
            {
                "symptoms": ["muscle spasms", "difficulty walking"],
                "diagnosis": "Multiple Sclerosis",
                "medications": ["disease-modifying therapies", "physical therapy"],
                "notes": "New symptoms of muscle spasms and difficulty walking. Diagnosed with multiple sclerosis. Prescribed disease-modifying therapies and recommended physical therapy."
            },
            {
                "symptoms": ["persistent cough", "chest pain"],
                "diagnosis": "Chronic Bronchitis",
                "medications": ["bronchodilators", "cough suppressants"],
                "notes": "Experiencing a persistent cough and chest pain. Diagnosed with chronic bronchitis. Prescribed bronchodilators and cough suppressants."
            },
            {
                "symptoms": ["fever", "sore throat"],
                "diagnosis": "Strep Throat",
                "medications": ["antibiotics", "pain relievers"],
                "notes": "Patient presents with fever and a sore throat. Diagnosed with strep throat. Prescribed antibiotics and pain relievers."
            },
            {
                "symptoms": ["swollen joints", "morning stiffness"],
                "diagnosis": "Rheumatoid Arthritis",
                "medications": ["DMARDs", "nonsteroidal anti-inflammatory drugs (NSAIDs)"],
                "notes": "Complaints of swollen joints and morning stiffness. Diagnosed with rheumatoid arthritis. Prescribed disease-modifying antirheumatic drugs (DMARDs) and NSAIDs."
            }
        ]
    }
}

import json

patient_data_str = json.dumps(patient_data)

input_text = patient_data_str.replace("{", "").replace("}", "").replace('"', '').replace("[", "").replace("]", "")

print(input_text)

from summarizer import Summarizer
model = Summarizer()

summary = model(input_text, ratio=0.2)
summary = model(input_text, num_sentences=500)

print(summary)

!pip install rouge-score

from rouge_score import rouge_scorer

scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'])
scores = scorer.score(input_text, summary)

print("ROUGE-1:", scores['rouge1'])
print("ROUGE-2:", scores['rouge2'])
print("ROUGE-L:", scores['rougeL'])